import type { ProductData } from "@/types"

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Spill Kits", href: "/spillkits" },
  { label: "Testimonials", href: "/testimonial" },
] as const

export const PRODUCTS: Record<string, ProductData[]> = {
  universal: [
    {
      id: "10L",
      name: "RESQ CHEMICAL ABSORBENT SPILL KIT - 10 LTR/2.6 GALLON",
      title: "All-in-One Spill Readiness",
      image: "/images/spillkit/universal-kit/universal10.jpeg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "6 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "1 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "1 piece" },
        { id: 4, description: "sponge wipes", qty: "1 piece" },
        { id: 5, description: "disposable bag with tie", qty: "2 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "disposable face mask", qty: "1 piece" },
        { id: 9, description: "pvc chemical apron", qty: "1 piece" },
        { id: 10, description: "instruction sheet", qty: "1 piece" },
        { id: 11, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "17 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "15L",
      name: "RESQ UNIVERSAL ABSORBENT SPILL KIT - 15 LTR/4 GALLON",
      title: "All-in-One Spill Readiness",
      image: "/images/spillkit/universal-kit/universal15.png",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "12 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "1 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "1 piece" },
        { id: 4, description: "sponge wipes", qty: "1 piece" },
        { id: 5, description: "disposable bag with tie", qty: "2 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "disposable face mask", qty: "1 piece" },
        { id: 9, description: "pvc chemical apron", qty: "1 piece" },
        { id: 10, description: "instruction sheet", qty: "1 piece" },
        { id: 11, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "23 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "30L",
      name: "RESQ UNIVERSAL ABSORBENT SPILL KIT - 30 LTR/8 GALLON",
      title: "All-in-One Spill Readiness",
      image: "/images/spillkit/universal-kit/universal30.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "24 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "2 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "2 piece" },
        { id: 4, description: "sponge wipes", qty: "2 piece" },
        { id: 5, description: "disposable bag with tie", qty: "3 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "disposable face mask", qty: "1 piece" },
        { id: 9, description: "pvc chemical apron", qty: "1 piece" },
        { id: 10, description: "instruction sheet", qty: "1 piece" },
        { id: 11, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "39 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "50L",
      name: "RESQ UNIVERSAL ABSORBENT SPILL KIT - 50 LTR/13 GALLON",
      title: "All-in-One Spill Readiness",
      image: "/images/spillkit/universal-kit/universal50.png",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "40 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "3 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "3 piece" },
        { id: 4, description: "sponge wipes", qty: "3 piece" },
        { id: 5, description: "disposable bag with tie", qty: "4 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "pvc chemical apron", qty: "1 piece" },
        { id: 9, description: "instruction sheet", qty: "1 piece" },
        { id: 10, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "58 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "75L",
      name: "RESQ UNIVERSAL ABSORBENT SPILL KIT - 75 LTR/20 GALLON",
      title: "All-in-One Spill Readiness",
      image: "/images/spillkit/universal-kit/universal75.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "56 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "4 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "4 piece" },
        { id: 4, description: "sponge wipes", qty: "3 piece" },
        { id: 5, description: "disposable bag with tie", qty: "5 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "pvc chemical apron", qty: "1 piece" },
        { id: 9, description: "venus half face mask (V500 + V7500)", qty: "1 piece" },
        { id: 10, description: "eyewash bottle", qty: "1 piece" },
        { id: 11, description: "barricading tape", qty: "1 roll" },
        { id: 12, description: "dust pan", qty: "1 piece" },
        { id: 13, description: "wiper", qty: "1 piece" },
        { id: 14, description: "instruction sheet", qty: "1 piece" },
        { id: 15, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "82 piece",
        dimensions: "20 x 16 x 15 inch",
        weight: "approx 6.8 kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "120L",
      name: "RESQ UNIVERSAL ABSORBENT SPILL KIT - 120 LTR/32 GALLON",
      title: "All-in-One Spill Readiness",
      image: "/images/spillkit/universal-kit/universal120.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "100 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "6 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "6 piece" },
        { id: 4, description: "sponge wipes", qty: "5 piece" },
        { id: 5, description: "disposable bag with tie", qty: "8 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "2 pair" },
        { id: 7, description: "chemical splash google", qty: "2 piece" },
        { id: 8, description: "pvc chemical apron", qty: "2 piece" },
        { id: 9, description: "venus half face mask (V500 + V7500)", qty: "1 piece" },
        { id: 10, description: "eyewash bottle", qty: "1 piece" },
        { id: 11, description: "barricading tape", qty: "1 roll" },
        { id: 12, description: "dust pan", qty: "1 piece" },
        { id: 13, description: "wiper", qty: "1 piece" },
        { id: 14, description: "instruction sheet", qty: "1 piece" },
        { id: 15, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "137 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
  ],
  oil: [
    {
      id: "10L",
      name: "RESQ OIL ABSORBENT SPILL KIT - 10 LTR/2.6 GALLON",
      title: "Prepare for Oil Spills with our Comprehensive Kits",
      image: "/images/spillkit/oil-kit/oil10.jpeg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "6 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "1 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "1 piece" },
        { id: 4, description: "sponge wipes", qty: "1 piece" },
        { id: 5, description: "disposable bag with tie", qty: "2 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "disposable face mask", qty: "1 piece" },
        { id: 9, description: "pvc chemical apron", qty: "1 piece" },
        { id: 10, description: "instruction sheet", qty: "1 piece" },
        { id: 11, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "17 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "15L",
      name: "RESQ OIL ABSORBENT SPILL KIT - 15 LTR/4 GALLON",
      title: "Prepare for Oil Spills with our Comprehensive Kits",
      image: "/images/spillkit/oil-kit/oil15.png",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "12 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "1 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "1 piece" },
        { id: 4, description: "sponge wipes", qty: "1 piece" },
        { id: 5, description: "disposable bag with tie", qty: "2 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "disposable face mask", qty: "1 piece" },
        { id: 9, description: "pvc chemical apron", qty: "1 piece" },
        { id: 10, description: "instruction sheet", qty: "1 piece" },
        { id: 11, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "23 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "30L",
      name: "RESQ OIL ABSORBENT SPILL KIT - 30 LTR/8 GALLON",
      title: "Prepare for Oil Spills with our Comprehensive Kits",
      image: "/images/spillkit/oil-kit/oil30.png",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "24 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "2 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "2 piece" },
        { id: 4, description: "sponge wipes", qty: "2 piece" },
        { id: 5, description: "disposable bag with tie", qty: "3 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "disposable face mask", qty: "1 piece" },
        { id: 9, description: "pvc chemical apron", qty: "1 piece" },
        { id: 10, description: "instruction sheet", qty: "1 piece" },
        { id: 11, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "39 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "50L",
      name: "RESQ OIL ABSORBENT SPILL KIT - 50 LTR/13 GALLON",
      title: "Prepare for Oil Spills with our Comprehensive Kits",
      image: "/images/spillkit/oil-kit/oil50.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "40 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "3 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "3 piece" },
        { id: 4, description: "sponge wipes", qty: "3 piece" },
        { id: 5, description: "disposable bag with tie", qty: "4 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "pvc chemical apron", qty: "1 piece" },
        { id: 9, description: "instruction sheet", qty: "1 piece" },
        { id: 10, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "58 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "75L",
      name: "RESQ OIL ABSORBENT SPILL KIT - 75 LTR/20 GALLON",
      title: "Prepare for Oil Spills with our Comprehensive Kits",
      image: "/images/spillkit/oil-kit/oil75.jpeg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "56 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "4 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "4 piece" },
        { id: 4, description: "sponge wipes", qty: "3 piece" },
        { id: 5, description: "disposable bag with tie", qty: "5 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "pvc chemical apron", qty: "1 piece" },
        { id: 9, description: "instruction sheet", qty: "1 piece" },
        { id: 10, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "80 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "120L",
      name: "RESQ OIL ABSORBENT SPILL KIT - 120 LTR/32 GALLON",
      title: "Prepare for Oil Spills with our Comprehensive Kits",
      image: "/images/spillkit/oil-kit/oil120.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "100 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "6 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "6 piece" },
        { id: 4, description: "sponge wipes", qty: "5 piece" },
        { id: 5, description: "disposable bag with tie", qty: "8 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "2 pair" },
        { id: 7, description: "chemical splash google", qty: "2 piece" },
        { id: 8, description: "pvc chemical apron", qty: "2 piece" },
        { id: 9, description: "instruction sheet", qty: "1 piece" },
        { id: 10, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "133 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
  ],
  chemical: [
    {
      id: "10L",
      name: "RESQ CHEMICAL ABSORBENT SPILL KIT - 10 LTR/2.6 GALLON",
      title: "Stay Prepared and Minimize Risk with our Chemical Spill Kits",
      image: "/images/spillkit/chemical-kit/chemical10.jpeg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "6 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "1 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "1 piece" },
        { id: 4, description: "sponge wipes", qty: "1 piece" },
        { id: 5, description: "disposable bag with tie", qty: "2 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "disposable face mask", qty: "1 piece" },
        { id: 9, description: "pvc chemical apron", qty: "1 piece" },
        { id: 10, description: "instruction sheet", qty: "1 piece" },
        { id: 11, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "17 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "15L",
      name: "RESQ CHEMICAL ABSORBENT SPILL KIT - 15 LTR/4 GALLON",
      title: "Stay Prepared and Minimize Risk with our Chemical Spill Kits",
      image: "/images/spillkit/chemical-kit/chemical15.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "12 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "1 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "1 piece" },
        { id: 4, description: "sponge wipes", qty: "1 piece" },
        { id: 5, description: "disposable bag with tie", qty: "2 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "disposable face mask", qty: "1 piece" },
        { id: 9, description: "pvc chemical apron", qty: "1 piece" },
        { id: 10, description: "instruction sheet", qty: "1 piece" },
        { id: 11, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "23 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "30L",
      name: "RESQ CHEMICAL ABSORBENT SPILL KIT - 30 LTR/8 GALLON",
      title: "Stay Prepared and Minimize Risk with our Chemical Spill Kits",
      image: "/images/spillkit/chemical-kit/chemical30.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "24 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "2 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "2 piece" },
        { id: 4, description: "sponge wipes", qty: "2 piece" },
        { id: 5, description: "disposable bag with tie", qty: "3 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "disposable face mask", qty: "1 piece" },
        { id: 9, description: "pvc chemical apron", qty: "1 piece" },
        { id: 10, description: "instruction sheet", qty: "1 piece" },
        { id: 11, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "39 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "50L",
      name: "RESQ CHEMICAL ABSORBENT SPILL KIT - 50 LTR/13 GALLON",
      title: "Stay Prepared and Minimize Risk with our Chemical Spill Kits",
      image: "/images/spillkit/chemical-kit/chemical50.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "40 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "3 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "3 piece" },
        { id: 4, description: "sponge wipes", qty: "3 piece" },
        { id: 5, description: "disposable bag with tie", qty: "4 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "pvc chemical apron", qty: "1 piece" },
        { id: 9, description: "instruction sheet", qty: "1 piece" },
        { id: 10, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "58 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "75L",
      name: "RESQ CHEMICAL ABSORBENT SPILL KIT - 75 LTR/20 GALLON",
      title: "Stay Prepared and Minimize Risk with our Chemical Spill Kits",
      image: "/images/spillkit/chemical-kit/chemical75.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "56 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "4 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "4 piece" },
        { id: 4, description: "sponge wipes", qty: "3 piece" },
        { id: 5, description: "disposable bag with tie", qty: "5 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "1 pair" },
        { id: 7, description: "chemical splash google", qty: "1 piece" },
        { id: 8, description: "pvc chemical apron", qty: "1 piece" },
        { id: 9, description: "instruction sheet", qty: "1 piece" },
        { id: 10, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "80 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
    {
      id: "120L",
      name: "RESQ CHEMICAL ABSORBENT SPILL KIT - 120 LTR/32 GALLON",
      title: "Stay Prepared and Minimize Risk with our Chemical Spill Kits",
      image: "/images/spillkit/chemical-kit/chemical120.jpg",
      rows: [
        { id: 1, description: "absorbent pads (300 gsm, 40 X 50 cm)", qty: "100 piece" },
        { id: 2, description: "absorbent pillow (30 x 30 cm)", qty: "6 piece" },
        { id: 3, description: "absorbent socks (8 cm dia x 1.2 mtr length)", qty: "6 piece" },
        { id: 4, description: "sponge wipes", qty: "5 piece" },
        { id: 5, description: "disposable bag with tie", qty: "8 piece" },
        { id: 6, description: "nitrile rubber gloves", qty: "2 pair" },
        { id: 7, description: "chemical splash google", qty: "2 piece" },
        { id: 8, description: "pvc chemical apron", qty: "2 piece" },
        { id: 9, description: "instruction sheet", qty: "1 piece" },
        { id: 10, description: "storage bag", qty: "1 piece" },
      ],
      specs: {
        totalContents: "133 piece",
        dimensions: "? inch",
        weight: "approx ? kg",
        price: "?",
        gstExtra: "18%",
      },
    },
  ],
}
